spring:
  control-db:
    username: sa
    password:
    driverClassName: org.h2.Driver
    jdbcUrl: jdbc:h2:mem:controldb
  target-db:
    username: postgres
    password: Firs$7job
    driverClassName: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://localhost:5432/pgDatabase
  source-db:
    username: root
    password: Firs$7job
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/mysql